# Generated by Django 4.1 on 2022-08-29 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fni_page', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_profile',
        ),
    ]
