# Generated by Django 4.1 on 2022-08-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fni_page', '0003_rename_user_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='email',
            new_name='occupation_and_monthly_saving',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='monthly_saving',
        ),
    ]
